spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${db-url:jdbc:postgresql://localhost:5432/passport}
    username: ${db-username:postgres}
    password: ${db-password:Vaifery111}
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect

    # ?????? ????? ??????????????????, ???? ????????? ?? ?????????? ? ????? ????? ? ??? ??????? ??????????? ?? ?????
