spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${db-url:jdbc:postgresql://localhost:5432/monolyth}
    username: ${db-username:postgres}
    password: ${db-password:qwe}
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect



secrets:
  SECRET_KEY: 6A576D5A7134743777217A25432A462D4A614E645267556B5870327235753878
